apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conduitcontroller
  name: conduitcontroller
spec:
  replicas: ${#toInt( parameters.replicas )}
  selector:
    matchLabels:
      app: conduitcontroller
  template:
    metadata:
      annotations:
        ad.datadoghq.com/conduitcontroller.logs: '[{"source":"conduit","service":"controller"}]'
      labels:
        app: conduitcontroller
    spec:
      containers:
        - image: 'leefaus/spring-boot-demo'
          name: conduitcontroller
          ports:
            - containerPort: ${#toInt(parameters.containerPort)}
          env:
            - name: POSTGRES_HOST
              value: "realworld.c9gbtmhbewq7.us-west-2.rds.amazonaws.com"
            - name: POSTGRES_USER
              value: "realworld"
            - name: POSTGRES_PASS
              value: "r3@lw0rld"
