apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: realworldbackend
  name: realworldbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworldbackend
  template:
    metadata:
      labels:
        app: realworldbackend
    spec:
      containers:
        - image: 'leefaus/spring-boot-demo'
          name: realworldbackend
          ports:
            - containerPort: ${#toInt(parameters.containerPort)}

