apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: realworldbackend
  name: realworldbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworldbackend
  template:
    metadata:
      labels:
        app: realworldbackend
    spec:
      containers:
        - image: 'leefaus/spring-boot-demo'
          name: realworldbackend
          ports:
            - containerPort: ${#toInt(parameters.containerPort)}
          env:
            - name: POSTGRES_HOST
              value: "realworld.c9gbtmhbewq7.us-west-2.rds.amazonaws.com"
            - name: POSTGRES_USER
              value: "realworld"
            - name: POSTGRES_PASS
              value: "r3@lw0rld"
