apiVersion: v1
kind: Service
metadata:
  name: springbootdemo
spec:
  ports:
    - port: ${#toInt(parameters.loadbalancerPort)}
      protocol: TCP
      targetPort: ${#toInt(parameters.containerPort)}
  selector:
    redblackapp: realworldbackend
  type: LoadBalancer