apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: springbootdemo
  name: springbootdemo
  namespace: prod
spec:
  replicas: ${#toInt( parameters.replicas )}
  selector:
    matchLabels:
      app: springbootdemo
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:
        - image: 'leefaus/spring-boot-demo'
          name: springbootdemo
          ports:
            - containerPort: ${#toInt(parameters.containerPort)}
