apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: conduitcontroller
  name: conduitcontroller
  namespace: prod
spec:
  replicas: ${#toInt( parameters.replicas )}
  selector:
    matchLabels:
      app: conduitcontroller
  template:
    metadata:
      labels:
        app: conduitcontroller
    spec:
      containers:
        - image: 'leefaus/spring-boot-demo'
          name: conduitcontroller
          ports:
            - containerPort: ${#toInt(parameters.containerPort)}
