apiVersion: v1
kind: Service
metadata:
  name: conduitcontroller
spec:
  ports:
    - port: ${#toInt(parameters.loadbalancerPort)}
      protocol: TCP
      targetPort: ${#toInt(parameters.containerPort)}
  selector:
    app: conduitcontroller
  type: LoadBalancer